# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_sol.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(252, 184)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblMsg = QtWidgets.QLabel(self.centralwidget)
        self.lblMsg.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.lblMsg.setObjectName("lblMsg")
        self.btnHello = QtWidgets.QPushButton(self.centralwidget)
        self.btnHello.setGeometry(QtCore.QRect(30, 80, 91, 41))
        self.btnHello.setObjectName("btnHello")
        self.btnWorld = QtWidgets.QPushButton(self.centralwidget)
        self.btnWorld.setGeometry(QtCore.QRect(140, 80, 91, 41))
        self.btnWorld.setObjectName("btnWorld")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnWorld.clicked.connect(MainWindow.print_world)
        self.btnHello.clicked.connect(MainWindow.print_hello)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblMsg.setText(_translate("MainWindow", "message"))
        self.btnHello.setText(_translate("MainWindow", "Hello"))
        self.btnWorld.setText(_translate("MainWindow", "World"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
