# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(274, 227)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblColor = QtWidgets.QLabel(self.centralwidget)
        self.lblColor.setGeometry(QtCore.QRect(150, 20, 101, 91))
        self.lblColor.setFrameShape(QtWidgets.QFrame.Box)
        self.lblColor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblColor.setText("")
        self.lblColor.setObjectName("lblColor")
        self.lblState = QtWidgets.QLabel(self.centralwidget)
        self.lblState.setGeometry(QtCore.QRect(150, 120, 101, 91))
        self.lblState.setFrameShape(QtWidgets.QFrame.Box)
        self.lblState.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblState.setText("")
        self.lblState.setObjectName("lblState")
        self.btnPush = QtWidgets.QPushButton(self.centralwidget)
        self.btnPush.setGeometry(QtCore.QRect(30, 20, 101, 91))
        self.btnPush.setObjectName("btnPush")
        self.btnToggle = QtWidgets.QPushButton(self.centralwidget)
        self.btnToggle.setGeometry(QtCore.QRect(30, 120, 101, 91))
        self.btnToggle.setCheckable(True)
        self.btnToggle.setObjectName("btnToggle")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnPush.setText(_translate("MainWindow", "색상 변경"))
        self.btnToggle.setText(_translate("MainWindow", "OFF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
