# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(311, 200)
        MainWindow.setMinimumSize(QtCore.QSize(0, 200))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btngetSaveFile = QtWidgets.QPushButton(self.centralwidget)
        self.btngetSaveFile.setObjectName("btngetSaveFile")
        self.gridLayout.addWidget(self.btngetSaveFile, 2, 0, 1, 1)
        self.lblOpenFileName = QtWidgets.QLabel(self.centralwidget)
        self.lblOpenFileName.setTextFormat(QtCore.Qt.RichText)
        self.lblOpenFileName.setOpenExternalLinks(True)
        self.lblOpenFileName.setObjectName("lblOpenFileName")
        self.gridLayout.addWidget(self.lblOpenFileName, 0, 1, 1, 1)
        self.btngetOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.btngetOpenFile.setObjectName("btngetOpenFile")
        self.gridLayout.addWidget(self.btngetOpenFile, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.linePath = QtWidgets.QLineEdit(self.centralwidget)
        self.linePath.setObjectName("linePath")
        self.gridLayout.addWidget(self.linePath, 3, 1, 1, 1)
        self.btnExitDir = QtWidgets.QPushButton(self.centralwidget)
        self.btnExitDir.setObjectName("btnExitDir")
        self.gridLayout.addWidget(self.btnExitDir, 3, 0, 1, 1)
        self.lblSaveFileName = QtWidgets.QLabel(self.centralwidget)
        self.lblSaveFileName.setTextFormat(QtCore.Qt.RichText)
        self.lblSaveFileName.setOpenExternalLinks(True)
        self.lblSaveFileName.setObjectName("lblSaveFileName")
        self.gridLayout.addWidget(self.lblSaveFileName, 2, 1, 1, 1)
        self.linePathUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.linePathUrl.setObjectName("linePathUrl")
        self.gridLayout.addWidget(self.linePathUrl, 4, 1, 1, 1)
        self.btnExitDirUrl = QtWidgets.QPushButton(self.centralwidget)
        self.btnExitDirUrl.setObjectName("btnExitDirUrl")
        self.gridLayout.addWidget(self.btnExitDirUrl, 4, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 311, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btngetSaveFile.setText(_translate("MainWindow", "getSaveFile"))
        self.lblOpenFileName.setText(_translate("MainWindow", "선택파일 없음"))
        self.btngetOpenFile.setText(_translate("MainWindow", "getOpenFile"))
        self.label.setText(_translate("MainWindow", "선택된 경로 없음"))
        self.linePath.setText(_translate("MainWindow", "C:/Windows/"))
        self.btnExitDir.setText(_translate("MainWindow", "getExistingDirectory"))
        self.lblSaveFileName.setText(_translate("MainWindow", "선택파일 없음"))
        self.linePathUrl.setText(_translate("MainWindow", "file:///C:/Windows"))
        self.btnExitDirUrl.setText(_translate("MainWindow", "getExistingDirectoryUrl"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
