# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(348, 96)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFlat = QtWidgets.QPushButton(self.centralwidget)
        self.btnFlat.setGeometry(QtCore.QRect(230, 10, 100, 30))
        self.btnFlat.setAutoFillBackground(False)
        self.btnFlat.setStyleSheet("")
        self.btnFlat.setCheckable(False)
        self.btnFlat.setChecked(False)
        self.btnFlat.setFlat(True)
        self.btnFlat.setObjectName("btnFlat")
        self.btnDisable = QtWidgets.QPushButton(self.centralwidget)
        self.btnDisable.setEnabled(False)
        self.btnDisable.setGeometry(QtCore.QRect(120, 10, 100, 30))
        self.btnDisable.setObjectName("btnDisable")
        self.btnCheckable = QtWidgets.QPushButton(self.centralwidget)
        self.btnCheckable.setEnabled(True)
        self.btnCheckable.setGeometry(QtCore.QRect(10, 50, 100, 30))
        self.btnCheckable.setCheckable(True)
        self.btnCheckable.setObjectName("btnCheckable")
        self.btnPush = QtWidgets.QPushButton(self.centralwidget)
        self.btnPush.setEnabled(True)
        self.btnPush.setGeometry(QtCore.QRect(10, 10, 100, 30))
        self.btnPush.setObjectName("btnPush")
        self.btnAutoRepeat = QtWidgets.QPushButton(self.centralwidget)
        self.btnAutoRepeat.setEnabled(True)
        self.btnAutoRepeat.setGeometry(QtCore.QRect(120, 50, 100, 30))
        self.btnAutoRepeat.setAutoRepeat(True)
        self.btnAutoRepeat.setObjectName("btnAutoRepeat")
        self.btnDefault = QtWidgets.QPushButton(self.centralwidget)
        self.btnDefault.setEnabled(True)
        self.btnDefault.setGeometry(QtCore.QRect(230, 50, 100, 30))
        self.btnDefault.setAutoDefault(False)
        self.btnDefault.setDefault(False)
        self.btnDefault.setObjectName("btnDefault")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnFlat.setText(_translate("MainWindow", "flat"))
        self.btnFlat.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.btnDisable.setText(_translate("MainWindow", "enabled"))
        self.btnCheckable.setText(_translate("MainWindow", "checkable"))
        self.btnPush.setText(_translate("MainWindow", "push button"))
        self.btnPush.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.btnAutoRepeat.setText(_translate("MainWindow", "autoRepeat"))
        self.btnDefault.setText(_translate("MainWindow", "default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
