# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(317, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Hslider = QtWidgets.QSlider(self.centralwidget)
        self.Hslider.setGeometry(QtCore.QRect(20, 10, 211, 16))
        self.Hslider.setProperty("value", 0)
        self.Hslider.setSliderPosition(0)
        self.Hslider.setTracking(True)
        self.Hslider.setOrientation(QtCore.Qt.Horizontal)
        self.Hslider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Hslider.setObjectName("Hslider")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(80, 40, 141, 111))
        self.dial.setMaximum(50)
        self.dial.setPageStep(2)
        self.dial.setNotchTarget(10.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.lcdH = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdH.setGeometry(QtCore.QRect(240, 10, 64, 23))
        self.lcdH.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdH.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdH.setObjectName("lcdH")
        self.lcdDial = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdDial.setGeometry(QtCore.QRect(210, 80, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdDial.sizePolicy().hasHeightForWidth())
        self.lcdDial.setSizePolicy(sizePolicy)
        self.lcdDial.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdDial.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdDial.setObjectName("lcdDial")
        self.lcdV = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdV.setGeometry(QtCore.QRect(0, 170, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdV.sizePolicy().hasHeightForWidth())
        self.lcdV.setSizePolicy(sizePolicy)
        self.lcdV.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdV.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdV.setObjectName("lcdV")
        self.Vslider = QtWidgets.QSlider(self.centralwidget)
        self.Vslider.setGeometry(QtCore.QRect(21, 42, 16, 121))
        self.Vslider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Vslider.setMinimum(-100)
        self.Vslider.setMaximum(100)
        self.Vslider.setOrientation(QtCore.Qt.Vertical)
        self.Vslider.setObjectName("Vslider")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Vslider.valueChanged['int'].connect(self.lcdV.display) # type: ignore
        self.dial.valueChanged['int'].connect(self.lcdDial.display) # type: ignore
        self.Hslider.valueChanged['int'].connect(self.lcdH.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
