# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(443, 199)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btngetText = QtWidgets.QPushButton(self.centralwidget)
        self.btngetText.setObjectName("btngetText")
        self.gridLayout.addWidget(self.btngetText, 0, 0, 1, 1)
        self.btngetDouble = QtWidgets.QPushButton(self.centralwidget)
        self.btngetDouble.setObjectName("btngetDouble")
        self.gridLayout.addWidget(self.btngetDouble, 3, 0, 1, 1)
        self.btngetInt = QtWidgets.QPushButton(self.centralwidget)
        self.btngetInt.setObjectName("btngetInt")
        self.gridLayout.addWidget(self.btngetInt, 2, 0, 1, 1)
        self.lblgetInt = QtWidgets.QLabel(self.centralwidget)
        self.lblgetInt.setWordWrap(True)
        self.lblgetInt.setObjectName("lblgetInt")
        self.gridLayout.addWidget(self.lblgetInt, 2, 1, 1, 1)
        self.lblgetDouble = QtWidgets.QLabel(self.centralwidget)
        self.lblgetDouble.setWordWrap(True)
        self.lblgetDouble.setObjectName("lblgetDouble")
        self.gridLayout.addWidget(self.lblgetDouble, 3, 1, 1, 1)
        self.lblgetText = QtWidgets.QLabel(self.centralwidget)
        self.lblgetText.setObjectName("lblgetText")
        self.gridLayout.addWidget(self.lblgetText, 0, 1, 1, 1)
        self.btngetItem = QtWidgets.QPushButton(self.centralwidget)
        self.btngetItem.setObjectName("btngetItem")
        self.gridLayout.addWidget(self.btngetItem, 4, 0, 1, 1)
        self.lblgetItem = QtWidgets.QLabel(self.centralwidget)
        self.lblgetItem.setWordWrap(True)
        self.lblgetItem.setObjectName("lblgetItem")
        self.gridLayout.addWidget(self.lblgetItem, 4, 1, 1, 1)
        self.btngetTextMulti = QtWidgets.QPushButton(self.centralwidget)
        self.btngetTextMulti.setObjectName("btngetTextMulti")
        self.gridLayout.addWidget(self.btngetTextMulti, 5, 0, 1, 1)
        self.lblgetTextMulti = QtWidgets.QLabel(self.centralwidget)
        self.lblgetTextMulti.setWordWrap(True)
        self.lblgetTextMulti.setObjectName("lblgetTextMulti")
        self.gridLayout.addWidget(self.lblgetTextMulti, 5, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btngetText.setText(_translate("MainWindow", "getText"))
        self.btngetDouble.setText(_translate("MainWindow", "getDouble"))
        self.btngetInt.setText(_translate("MainWindow", "getInt"))
        self.lblgetInt.setText(_translate("MainWindow", "나이 :"))
        self.lblgetDouble.setText(_translate("MainWindow", "키 :"))
        self.lblgetText.setText(_translate("MainWindow", "이름 : "))
        self.btngetItem.setText(_translate("MainWindow", "getItem"))
        self.lblgetItem.setText(_translate("MainWindow", "취미 :"))
        self.btngetTextMulti.setText(_translate("MainWindow", "getTextMulti"))
        self.lblgetTextMulti.setText(_translate("MainWindow", "하고싶은 말 :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
