# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(254, 54)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCheckable = QtWidgets.QPushButton(self.centralwidget)
        self.btnCheckable.setEnabled(True)
        self.btnCheckable.setGeometry(QtCore.QRect(130, 10, 100, 30))
        self.btnCheckable.setCheckable(True)
        self.btnCheckable.setObjectName("btnCheckable")
        self.btnPush = QtWidgets.QPushButton(self.centralwidget)
        self.btnPush.setEnabled(True)
        self.btnPush.setGeometry(QtCore.QRect(10, 10, 100, 30))
        self.btnPush.setDefault(False)
        self.btnPush.setObjectName("btnPush")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCheckable.setText(_translate("MainWindow", "checkable"))
        self.btnPush.setText(_translate("MainWindow", "push button"))
        self.btnPush.setShortcut(_translate("MainWindow", "Ctrl+P"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
