# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 261)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCritical = QtWidgets.QPushButton(self.groupBox)
        self.btnCritical.setObjectName("btnCritical")
        self.verticalLayout.addWidget(self.btnCritical)
        self.btnInfo = QtWidgets.QPushButton(self.groupBox)
        self.btnInfo.setObjectName("btnInfo")
        self.verticalLayout.addWidget(self.btnInfo)
        self.btnQuestion = QtWidgets.QPushButton(self.groupBox)
        self.btnQuestion.setObjectName("btnQuestion")
        self.verticalLayout.addWidget(self.btnQuestion)
        self.btnWarning = QtWidgets.QPushButton(self.groupBox)
        self.btnWarning.setObjectName("btnWarning")
        self.verticalLayout.addWidget(self.btnWarning)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnProperty = QtWidgets.QPushButton(self.groupBox_2)
        self.btnProperty.setObjectName("btnProperty")
        self.verticalLayout_2.addWidget(self.btnProperty)
        self.btnCritical_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCritical_2.setObjectName("btnCritical_2")
        self.verticalLayout_2.addWidget(self.btnCritical_2)
        self.btnInfo_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnInfo_2.setObjectName("btnInfo_2")
        self.verticalLayout_2.addWidget(self.btnInfo_2)
        self.btnQuestion_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnQuestion_2.setObjectName("btnQuestion_2")
        self.verticalLayout_2.addWidget(self.btnQuestion_2)
        self.btnWarning_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.btnWarning_2.setObjectName("btnWarning_2")
        self.verticalLayout_2.addWidget(self.btnWarning_2)
        self.btnButtonOverload = QtWidgets.QPushButton(self.groupBox_2)
        self.btnButtonOverload.setObjectName("btnButtonOverload")
        self.verticalLayout_2.addWidget(self.btnButtonOverload)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 363, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "static function"))
        self.btnCritical.setText(_translate("MainWindow", "critical"))
        self.btnInfo.setText(_translate("MainWindow", "information"))
        self.btnQuestion.setText(_translate("MainWindow", "question"))
        self.btnWarning.setText(_translate("MainWindow", "waring"))
        self.groupBox_2.setTitle(_translate("MainWindow", "property-based"))
        self.btnProperty.setText(_translate("MainWindow", "property-based API"))
        self.btnCritical_2.setText(_translate("MainWindow", "critical"))
        self.btnInfo_2.setText(_translate("MainWindow", "information"))
        self.btnQuestion_2.setText(_translate("MainWindow", "question"))
        self.btnWarning_2.setText(_translate("MainWindow", "waring"))
        self.btnButtonOverload.setText(_translate("MainWindow", "사용자 버튼 추가"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
