# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblImg = QtWidgets.QLabel(self.centralwidget)
        self.lblImg.setGeometry(QtCore.QRect(5, 5, 640, 480))
        self.lblImg.setFrameShape(QtWidgets.QFrame.Box)
        self.lblImg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblImg.setText("")
        self.lblImg.setObjectName("lblImg")
        self.lblPicture = QtWidgets.QLabel(self.centralwidget)
        self.lblPicture.setGeometry(QtCore.QRect(10, 490, 101, 61))
        self.lblPicture.setText("")
        self.lblPicture.setObjectName("lblPicture")
        self.btnTakePicture = QtWidgets.QPushButton(self.centralwidget)
        self.btnTakePicture.setGeometry(QtCore.QRect(240, 490, 151, 61))
        self.btnTakePicture.setObjectName("btnTakePicture")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTakePicture.setText(_translate("MainWindow", "Take a picture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
