# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 186)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialR = QtWidgets.QDial(self.centralwidget)
        self.dialR.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.dialR.setMaximum(255)
        self.dialR.setNotchTarget(5.0)
        self.dialR.setNotchesVisible(False)
        self.dialR.setObjectName("dialR")
        self.verticalLayout.addWidget(self.dialR)
        self.lcdR = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdR.sizePolicy().hasHeightForWidth())
        self.lcdR.setSizePolicy(sizePolicy)
        self.lcdR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdR.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdR.setObjectName("lcdR")
        self.verticalLayout.addWidget(self.lcdR)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialG = QtWidgets.QDial(self.centralwidget)
        self.dialG.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.dialG.setMaximum(255)
        self.dialG.setNotchTarget(10.0)
        self.dialG.setNotchesVisible(False)
        self.dialG.setObjectName("dialG")
        self.verticalLayout_2.addWidget(self.dialG)
        self.lcdG = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdG.sizePolicy().hasHeightForWidth())
        self.lcdG.setSizePolicy(sizePolicy)
        self.lcdG.setStyleSheet("")
        self.lcdG.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdG.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdG.setObjectName("lcdG")
        self.verticalLayout_2.addWidget(self.lcdG)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dialB = QtWidgets.QDial(self.centralwidget)
        self.dialB.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.dialB.setMaximum(255)
        self.dialB.setNotchTarget(20.0)
        self.dialB.setNotchesVisible(False)
        self.dialB.setObjectName("dialB")
        self.verticalLayout_3.addWidget(self.dialB)
        self.lcdB = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdB.sizePolicy().hasHeightForWidth())
        self.lcdB.setSizePolicy(sizePolicy)
        self.lcdB.setStyleSheet("")
        self.lcdB.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdB.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdB.setObjectName("lcdB")
        self.verticalLayout_3.addWidget(self.lcdB)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.lblColor = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblColor.sizePolicy().hasHeightForWidth())
        self.lblColor.setSizePolicy(sizePolicy)
        self.lblColor.setMinimumSize(QtCore.QSize(0, 30))
        self.lblColor.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lblColor.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lblColor.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblColor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColor.setObjectName("lblColor")
        self.verticalLayout_4.addWidget(self.lblColor)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.dialR.valueChanged['int'].connect(self.lcdR.display) # type: ignore
        self.dialG.valueChanged['int'].connect(self.lcdG.display) # type: ignore
        self.dialB.valueChanged['int'].connect(self.lcdB.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblColor.setText(_translate("MainWindow", "rgb(0, 0, 0)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
