# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.linIn = QtWidgets.QLineEdit(self.groupBox)
        self.linIn.setObjectName("linIn")
        self.verticalLayout_3.addWidget(self.linIn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.linSet = QtWidgets.QLineEdit(self.groupBox)
        self.linSet.setObjectName("linSet")
        self.horizontalLayout.addWidget(self.linSet)
        self.btnSet = QtWidgets.QPushButton(self.groupBox)
        self.btnSet.setObjectName("btnSet")
        self.horizontalLayout.addWidget(self.btnSet)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioPass = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPass.setChecked(True)
        self.radioPass.setObjectName("radioPass")
        self.radioEcho = QtWidgets.QButtonGroup(MainWindow)
        self.radioEcho.setObjectName("radioEcho")
        self.radioEcho.addButton(self.radioPass)
        self.horizontalLayout_4.addWidget(self.radioPass)
        self.radioNoecho = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioNoecho.setObjectName("radioNoecho")
        self.radioEcho.addButton(self.radioNoecho)
        self.horizontalLayout_4.addWidget(self.radioNoecho)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblMsg1 = QtWidgets.QLabel(self.groupBox_2)
        self.lblMsg1.setObjectName("lblMsg1")
        self.horizontalLayout_2.addWidget(self.lblMsg1)
        self.btnDisp = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDisp.sizePolicy().hasHeightForWidth())
        self.btnDisp.setSizePolicy(sizePolicy)
        self.btnDisp.setObjectName("btnDisp")
        self.horizontalLayout_2.addWidget(self.btnDisp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblMsg2 = QtWidgets.QLabel(self.groupBox_2)
        self.lblMsg2.setObjectName("lblMsg2")
        self.horizontalLayout_3.addWidget(self.lblMsg2)
        self.btnText = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnText.sizePolicy().hasHeightForWidth())
        self.btnText.setSizePolicy(sizePolicy)
        self.btnText.setObjectName("btnText")
        self.horizontalLayout_3.addWidget(self.btnText)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "signal"))
        self.linIn.setPlaceholderText(_translate("MainWindow", "Input Text..."))
        self.btnSet.setText(_translate("MainWindow", "setText"))
        self.groupBox_2.setTitle(_translate("MainWindow", "echo mode"))
        self.radioPass.setText(_translate("MainWindow", "Password"))
        self.radioNoecho.setText(_translate("MainWindow", "NoEcho"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "표시할 line edit"))
        self.lblMsg1.setText(_translate("MainWindow", ".displayText() 사용"))
        self.btnDisp.setText(_translate("MainWindow", "displayText"))
        self.lblMsg2.setText(_translate("MainWindow", ".text() 사용"))
        self.btnText.setText(_translate("MainWindow", "text()"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
