# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 222)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_4.setInputMask("")
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_4)
        self.Label_3 = QtWidgets.QLabel(self.centralwidget)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.LineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_5.setInputMask("")
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_5)
        self.Label_4 = QtWidgets.QLabel(self.centralwidget)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_3)
        self.Label_5 = QtWidgets.QLabel(self.centralwidget)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_2.setInputMask("")
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.iPLabel = QtWidgets.QLabel(self.centralwidget)
        self.iPLabel.setObjectName("iPLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.iPLabel)
        self.linIP = QtWidgets.QLineEdit(self.centralwidget)
        self.linIP.setInputMask("")
        self.linIP.setObjectName("linIP")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.linIP)
        self.verticalLayout.addLayout(self.formLayout)
        self.lblError = QtWidgets.QLabel(self.centralwidget)
        self.lblError.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblError.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblError.setObjectName("lblError")
        self.verticalLayout.addWidget(self.lblError)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Label.setText(_translate("MainWindow", "아이디"))
        self.LineEdit_4.setPlaceholderText(_translate("MainWindow", "AXQ1234 형식"))
        self.Label_3.setText(_translate("MainWindow", "전화번호"))
        self.LineEdit_5.setPlaceholderText(_translate("MainWindow", "010-213-2513 형식"))
        self.Label_4.setText(_translate("MainWindow", "국어점수"))
        self.LineEdit_3.setPlaceholderText(_translate("MainWindow", "0 ~ 100 사이"))
        self.Label_5.setText(_translate("MainWindow", "백분위"))
        self.LineEdit.setPlaceholderText(_translate("MainWindow", "0.00 ~ 100.00 사이"))
        self.Label_2.setText(_translate("MainWindow", "비밀번호"))
        self.LineEdit_2.setPlaceholderText(_translate("MainWindow", "숫자/문자 6자리"))
        self.iPLabel.setText(_translate("MainWindow", "IP주소"))
        self.linIP.setPlaceholderText(_translate("MainWindow", "255.255.255.255 형식"))
        self.lblError.setText(_translate("MainWindow", "invalid 항목 표시"))
        self.btnOK.setText(_translate("MainWindow", "확인"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
