# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 303)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lstItemFrom = QtWidgets.QListWidget(self.centralwidget)
        self.lstItemFrom.setDragEnabled(False)
        self.lstItemFrom.setDragDropOverwriteMode(False)
        self.lstItemFrom.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lstItemFrom.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstItemFrom.setAlternatingRowColors(True)
        self.lstItemFrom.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.lstItemFrom.setMovement(QtWidgets.QListView.Free)
        self.lstItemFrom.setProperty("isWrapping", False)
        self.lstItemFrom.setViewMode(QtWidgets.QListView.ListMode)
        self.lstItemFrom.setObjectName("lstItemFrom")
        self.verticalLayout_2.addWidget(self.lstItemFrom)
        self.lblFromSel = QtWidgets.QLabel(self.centralwidget)
        self.lblFromSel.setObjectName("lblFromSel")
        self.verticalLayout_2.addWidget(self.lblFromSel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.btnRemove = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemove.setObjectName("btnRemove")
        self.verticalLayout.addWidget(self.btnRemove)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstItemTo = QtWidgets.QListWidget(self.centralwidget)
        self.lstItemTo.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lstItemTo.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lstItemTo.setMovement(QtWidgets.QListView.Free)
        self.lstItemTo.setViewMode(QtWidgets.QListView.ListMode)
        self.lstItemTo.setObjectName("lstItemTo")
        self.horizontalLayout.addWidget(self.lstItemTo)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnUp = QtWidgets.QToolButton(self.centralwidget)
        self.btnUp.setArrowType(QtCore.Qt.UpArrow)
        self.btnUp.setObjectName("btnUp")
        self.verticalLayout_3.addWidget(self.btnUp)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnDown = QtWidgets.QToolButton(self.centralwidget)
        self.btnDown.setArrowType(QtCore.Qt.DownArrow)
        self.btnDown.setObjectName("btnDown")
        self.verticalLayout_3.addWidget(self.btnDown)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.lblToSel = QtWidgets.QLabel(self.centralwidget)
        self.lblToSel.setObjectName("lblToSel")
        self.verticalLayout_4.addWidget(self.lblToSel)
        self.lblToText = QtWidgets.QLabel(self.centralwidget)
        self.lblToText.setObjectName("lblToText")
        self.verticalLayout_4.addWidget(self.lblToText)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lstItemFrom.setSortingEnabled(True)
        self.lblFromSel.setText(_translate("MainWindow", "선택된 item수: 0"))
        self.btnAdd.setText(_translate("MainWindow", "->"))
        self.btnRemove.setText(_translate("MainWindow", "<-"))
        self.btnUp.setText(_translate("MainWindow", "..."))
        self.btnDown.setText(_translate("MainWindow", "..."))
        self.lblToSel.setText(_translate("MainWindow", "선택된 item수: 0"))
        self.lblToText.setText(_translate("MainWindow", "선택된 item: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
