# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(152, 118)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_Helloworld = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Helloworld.setGeometry(QtCore.QRect(40, 20, 81, 16))
        self.lbl_Helloworld.setObjectName("lbl_Helloworld")
        self.Btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_clear.setGeometry(QtCore.QRect(20, 50, 101, 41))
        self.Btn_clear.setObjectName("Btn_clear")
        self.Btn_clear.raise_()
        self.lbl_Helloworld.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Btn_clear.clicked.connect(self.lbl_Helloworld.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Helloworld.setText(_translate("MainWindow", "Hello World"))
        self.Btn_clear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
