# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setStyleSheet("\n"
"/* 전체 배경 (다크 모드) */\n"
"QMainWindow {\n"
"    background-color: #1e1e1e;\n"
"}\n"
"\n"
"/* 상단 결과창 스타일 */\n"
"QLabel#lblDisp {\n"
"    color: white;\n"
"    background-color: #252526;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font: 36pt \"맑은 고딕\";\n"
"}\n"
"\n"
"/* 기본 버튼 스타일 (숫자 및 점) */\n"
"QPushButton {\n"
"    border-radius: 15px;\n"
"    font: 16pt \"맑은 고딕\";\n"
"    color: white;\n"
"    background-color: #333333;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3e3e42;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"/* 연산자 버튼 스타일 (+, -, *, /, =) */\n"
"QPushButton#btnPlus, QPushButton#btnMinus, QPushButton#btnMul, QPushButton#btnDivide, QPushButton#btnResult {\n"
"    background-color: #ff9f0a;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 20pt;\n"
"}\n"
"QPushButton#btnPlus:hover, QPushButton#btnMinus:hover, QPushButton#btnMul:hover, QPushButton#btnDivide:hover, QPushButton#btnResult:hover {\n"
"    background-color: #ffb03a;\n"
"}\n"
"QPushButton#btnPlus:pressed, QPushButton#btnMinus:pressed, QPushButton#btnMul:pressed, QPushButton#btnDivide:pressed, QPushButton#btnResult:pressed {\n"
"    background-color: #cc7f08;\n"
"}\n"
"\n"
"/* 기능 버튼 스타일 (<-, C, (, )) */\n"
"QPushButton#btnC, QPushButton#btnBack, QPushButton#btnl, QPushButton#btnr {\n"
"    background-color: #a5a5a5;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton#btnC:hover, QPushButton#btnBack:hover, QPushButton#btnl:hover, QPushButton#btnr:hover {\n"
"    background-color: #b5b5b5;\n"
"}\n"
"QPushButton#btnC:pressed, QPushButton#btnBack:pressed, QPushButton#btnl:pressed, QPushButton#btnr:pressed {\n"
"    background-color: #858585;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblDisp = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDisp.sizePolicy().hasHeightForWidth())
        self.lblDisp.setSizePolicy(sizePolicy)
        self.lblDisp.setMinimumSize(QtCore.QSize(0, 90))
        self.lblDisp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDisp.setObjectName("lblDisp")
        self.verticalLayout.addWidget(self.lblDisp)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBack.sizePolicy().hasHeightForWidth())
        self.btnBack.setSizePolicy(sizePolicy)
        self.btnBack.setObjectName("btnBack")
        self.btnGroupOp = QtWidgets.QButtonGroup(MainWindow)
        self.btnGroupOp.setObjectName("btnGroupOp")
        self.btnGroupOp.addButton(self.btnBack)
        self.gridLayout.addWidget(self.btnBack, 0, 0, 1, 1)
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnC.sizePolicy().hasHeightForWidth())
        self.btnC.setSizePolicy(sizePolicy)
        self.btnC.setObjectName("btnC")
        self.btnGroupOp.addButton(self.btnC)
        self.gridLayout.addWidget(self.btnC, 0, 1, 1, 1)
        self.btnl = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnl.sizePolicy().hasHeightForWidth())
        self.btnl.setSizePolicy(sizePolicy)
        self.btnl.setObjectName("btnl")
        self.btnGroupDisp = QtWidgets.QButtonGroup(MainWindow)
        self.btnGroupDisp.setObjectName("btnGroupDisp")
        self.btnGroupDisp.addButton(self.btnl)
        self.gridLayout.addWidget(self.btnl, 0, 2, 1, 1)
        self.btnr = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnr.sizePolicy().hasHeightForWidth())
        self.btnr.setSizePolicy(sizePolicy)
        self.btnr.setObjectName("btnr")
        self.btnGroupDisp.addButton(self.btnr)
        self.gridLayout.addWidget(self.btnr, 0, 3, 1, 1)
        self.btnResult = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnResult.sizePolicy().hasHeightForWidth())
        self.btnResult.setSizePolicy(sizePolicy)
        self.btnResult.setObjectName("btnResult")
        self.btnGroupOp.addButton(self.btnResult)
        self.gridLayout.addWidget(self.btnResult, 0, 4, 5, 1)
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn7.sizePolicy().hasHeightForWidth())
        self.btn7.setSizePolicy(sizePolicy)
        self.btn7.setObjectName("btn7")
        self.btnGroupDisp.addButton(self.btn7)
        self.gridLayout.addWidget(self.btn7, 1, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn8.sizePolicy().hasHeightForWidth())
        self.btn8.setSizePolicy(sizePolicy)
        self.btn8.setObjectName("btn8")
        self.btnGroupDisp.addButton(self.btn8)
        self.gridLayout.addWidget(self.btn8, 1, 1, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn9.sizePolicy().hasHeightForWidth())
        self.btn9.setSizePolicy(sizePolicy)
        self.btn9.setObjectName("btn9")
        self.btnGroupDisp.addButton(self.btn9)
        self.gridLayout.addWidget(self.btn9, 1, 2, 1, 1)
        self.btnDivide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDivide.sizePolicy().hasHeightForWidth())
        self.btnDivide.setSizePolicy(sizePolicy)
        self.btnDivide.setObjectName("btnDivide")
        self.btnGroupDisp.addButton(self.btnDivide)
        self.gridLayout.addWidget(self.btnDivide, 1, 3, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn4.sizePolicy().hasHeightForWidth())
        self.btn4.setSizePolicy(sizePolicy)
        self.btn4.setObjectName("btn4")
        self.btnGroupDisp.addButton(self.btn4)
        self.gridLayout.addWidget(self.btn4, 2, 0, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn5.sizePolicy().hasHeightForWidth())
        self.btn5.setSizePolicy(sizePolicy)
        self.btn5.setObjectName("btn5")
        self.btnGroupDisp.addButton(self.btn5)
        self.gridLayout.addWidget(self.btn5, 2, 1, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn6.sizePolicy().hasHeightForWidth())
        self.btn6.setSizePolicy(sizePolicy)
        self.btn6.setObjectName("btn6")
        self.btnGroupDisp.addButton(self.btn6)
        self.gridLayout.addWidget(self.btn6, 2, 2, 1, 1)
        self.btnMul = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMul.sizePolicy().hasHeightForWidth())
        self.btnMul.setSizePolicy(sizePolicy)
        self.btnMul.setObjectName("btnMul")
        self.btnGroupDisp.addButton(self.btnMul)
        self.gridLayout.addWidget(self.btnMul, 2, 3, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn1.sizePolicy().hasHeightForWidth())
        self.btn1.setSizePolicy(sizePolicy)
        self.btn1.setObjectName("btn1")
        self.btnGroupDisp.addButton(self.btn1)
        self.gridLayout.addWidget(self.btn1, 3, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn2.sizePolicy().hasHeightForWidth())
        self.btn2.setSizePolicy(sizePolicy)
        self.btn2.setObjectName("btn2")
        self.btnGroupDisp.addButton(self.btn2)
        self.gridLayout.addWidget(self.btn2, 3, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn3.sizePolicy().hasHeightForWidth())
        self.btn3.setSizePolicy(sizePolicy)
        self.btn3.setObjectName("btn3")
        self.btnGroupDisp.addButton(self.btn3)
        self.gridLayout.addWidget(self.btn3, 3, 2, 1, 1)
        self.btnPlus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlus.sizePolicy().hasHeightForWidth())
        self.btnPlus.setSizePolicy(sizePolicy)
        self.btnPlus.setObjectName("btnPlus")
        self.btnGroupDisp.addButton(self.btnPlus)
        self.gridLayout.addWidget(self.btnPlus, 3, 3, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn0.sizePolicy().hasHeightForWidth())
        self.btn0.setSizePolicy(sizePolicy)
        self.btn0.setObjectName("btn0")
        self.btnGroupDisp.addButton(self.btn0)
        self.gridLayout.addWidget(self.btn0, 4, 0, 1, 2)
        self.btnDot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDot.sizePolicy().hasHeightForWidth())
        self.btnDot.setSizePolicy(sizePolicy)
        self.btnDot.setObjectName("btnDot")
        self.btnGroupDisp.addButton(self.btnDot)
        self.gridLayout.addWidget(self.btnDot, 4, 2, 1, 1)
        self.btnMinus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMinus.sizePolicy().hasHeightForWidth())
        self.btnMinus.setSizePolicy(sizePolicy)
        self.btnMinus.setObjectName("btnMinus")
        self.btnGroupDisp.addButton(self.btnMinus)
        self.gridLayout.addWidget(self.btnMinus, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "모던 계산기"))
        self.lblDisp.setText(_translate("MainWindow", "0"))
        self.btnBack.setText(_translate("MainWindow", "←"))
        self.btnBack.setShortcut(_translate("MainWindow", "Backspace"))
        self.btnC.setText(_translate("MainWindow", "C"))
        self.btnl.setText(_translate("MainWindow", "("))
        self.btnl.setShortcut(_translate("MainWindow", "("))
        self.btnr.setText(_translate("MainWindow", ")"))
        self.btnr.setShortcut(_translate("MainWindow", ")"))
        self.btnResult.setText(_translate("MainWindow", "="))
        self.btnResult.setShortcut(_translate("MainWindow", "Enter"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn7.setShortcut(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn8.setShortcut(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn9.setShortcut(_translate("MainWindow", "9"))
        self.btnDivide.setText(_translate("MainWindow", "÷"))
        self.btnDivide.setShortcut(_translate("MainWindow", "/"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn4.setShortcut(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn5.setShortcut(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn6.setShortcut(_translate("MainWindow", "6"))
        self.btnMul.setText(_translate("MainWindow", "×"))
        self.btnMul.setShortcut(_translate("MainWindow", "*"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn1.setShortcut(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn2.setShortcut(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn3.setShortcut(_translate("MainWindow", "3"))
        self.btnPlus.setText(_translate("MainWindow", "+"))
        self.btnPlus.setShortcut(_translate("MainWindow", "+"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn0.setShortcut(_translate("MainWindow", "0"))
        self.btnDot.setText(_translate("MainWindow", "."))
        self.btnDot.setShortcut(_translate("MainWindow", "."))
        self.btnMinus.setText(_translate("MainWindow", "-"))
        self.btnMinus.setShortcut(_translate("MainWindow", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
